### ISSUE TITLE
Work out how to remove compute_fqdn

### ISSUE THREAD

**Issue by rbradford** [ciao-project/ciao#1138]
As part of #991 a commit was added to have ansible specify the controller fqdn so that it could be used in Ciao API entry points.

We should investigate if we can remove this (and the image one too) by trying to read the name from the cert.

**Comment by tpepper** [comment]
I think we could do roughly what's in PR#1139.  But instead of using the ssntp cert for controller, we'd use compute_cert.  But that in turn means we need to not specify just the key file in compute_cert, but rather an x509 structured cert which includes the key.  This will mean changes to ansible and singlevm and documentation.
