### ISSUE TITLE
ciao-down: file sharing only works for first user on a host computer

### ISSUE THREAD

**Issue by markdryan** [ciao-project/ciao#1380]
It seems that the passthrough security model only works properly if the users in both the host and the guest have the same uids and gids.  This is the case for the first user on the host but not for other users.  If the ids mismatch, you won't be able to write to the shared folder from the guest.

**Comment by markdryan** [comment]
@grahamwhaley This may have been the cause of your 9P issues with ciao-down.

**Comment by grahamwhaley** [comment]
Hi @markdryan iirc, at the time, the security issues I had were because I needed to run some stuff inside ciao-down as root that was writing/reading to files on the 9pfs mount ($GOPATH) - and `root` is special, possibly even in the passthrough mode. I bypassed the issue with `security_model=none`, as I 'knew what I was doing'.
Mapping UIDs from host to client and back is always a bane of VM/containerisation :-)

**Comment by markdryan** [comment]
Moved to https://github.com/intel/ccloudvm/issues/15
