### ISSUE TITLE
workloads can be started when cluster is not ready

### ISSUE THREAD

**Issue by kaccardi** [ciao-project/ciao#622]
If a network node hasn't finished with something that os-prepare asked it to do (for example, because it's going to have to timeout due to proxy issues), a workload could be started but the network node is unable to launch a CNCI. Presumably this issue could happen if for whatever reason anything is taking a while to get started. should we have some kind of minimum bar that controller sets for cluster health that would prevent workload start commands, or should we instead leave it the way it is and just have the command rejected at the scheduler with "no cnci".

**Comment by tpepper** [comment]
I think in the short term reject the job.

But revisit when scheduler can queue (https://github.com/01org/ciao/issues/99) and then I can implement a "waiting for cnci" flag on my queued objects and flush those jobs when their cnci arrives.

**Comment by kaccardi** [comment]
think this might be a bug in os-prepare design. did network node check into the scheduler, but then couldn't launch a workload? needs more investigation.

**Comment by tpepper** [comment]
It's scheduler and launcher and ssntp and config and os-prepare.  os-prepare gives a function to call when you want to get ready to run.  But we plumbed that os-prepare after the ssntp connection so config data can come in and launcher can know what type of launcher it is.  Node connectivity to the server doesn't mean the node is ready for action.

**Comment by rbradford** [comment]
I don't think this will cause problems any longer due to the the new CNCI manager behaviour with cnci start failure. If i simulate this problem by having no network node I get the following message:

F0927 14:19:15.508511   27757 instance.go:533] ciao-cli FATAL: HTTP Error [500] for [POST https://ciao-ctl:8889/v2.1/57d8ae9a-eb31-4126-a492-9d35b7e0ac29/servers]: {"error":{"code":500,"name":"Internal Server Error","message":"Error creating instance: expecting concentrator added got cnci start failure"}}
goroutine 1 [running]:

I can then proceed to try and start the instance again once the network node is up and it will then proceed.
